### ISSUE TITLE
TypeError: Cannot read property 'namespace' of undefined

### ISSUE THREAD

**Issue by julianomoreira** [node-base/base-cli#4]
We ran into an issue with Assemble after the 0.4.23 update. Our project won't load and gulp will not run. Not sure the root cause of this but I'm posting it here. Thanks!

```
 app.debug.namespace += ':commands';
           ^
TypeError: Cannot read property 'namespace' of undefined
    at module.exports (/Users/z0019rb/dev/design-systems/designsystems-site/node_modules/assemble/node_modules/base-cli/lib/cli.js:7:12)
    at Assemble.<anonymous> (/Users/z0019rb/dev/design-systems/designsystems-site/node_modules/assemble/node_modules/base-cli/index.js:21:5)
    at Assemble.use (/Users/z0019rb/dev/design-systems/designsystems-site/node_modules/assemble/node_modules/assemble-core/node_modules/templates/node_modules/base-plugins/index.js:93:21)
    at Assemble.<anonymous> (/Users/z0019rb/dev/design-systems/designsystems-site/node_modules/assemble/lib/cli.js:16:11)
    at Assemble.use (/Users/z0019rb/dev/design-systems/designsystems-site/node_modules/assemble/node_modules/assemble-core/node_modules/templates/node_modules/base-plugins/index.js:93:21)
    at enable (/Users/z0019rb/dev/design-systems/designsystems-site/node_modules/assemble/index.js:97:11)
    at Assemble.initPlugins (/Users/z0019rb/dev/design-systems/designsystems-site/node_modules/assemble/index.js:92:3)
    at new Assemble (/Users/z0019rb/dev/design-systems/designsystems-site/node_modules/assemble/index.js:34:8)
    at Assemble (/Users/z0019rb/dev/design-systems/designsystems-site/node_modules/assemble/index.js:26:12)
    at Object.<anonymous> (/Users/z0019rb/dev/design-systems/designsystems-site/gulpfile.js:25:11)`
```

**Comment by julianomoreira** [comment]
@jonschlinkert Let me know if this is the right forum for this.

**Comment by doowb** [comment]
@julianomoreira which version of assemble are you using? I just pulled down everything into a fresh directory (`npm i assemble`) and I'm not having any problems.

Also, can you post your `gulpfile`?

**Comment by julianomoreira** [comment]
Hello @doowb , we're using assemble 0.8.0.

Here it is our gulpfile:

`{
  "devDependencies": {
    "@alrra/travis-scripts": "^1.1.1",
    "apache-server-configs": "2.14.0",
    "archiver": "^0.21.0",
    "autoprefixer": "^6.3.1",
    "browser-sync": "^2.11.1",
    "del": "^2.0.2",
    "glob": "^6.0.1",
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^3.0.2",
    "gulp-header": "^1.2.2",
    "gulp-jscs": "^3.0.1",
    "gulp-jshint": "^2.0.0",
    "gulp-load-plugins": "^1.1.0",
    "gulp-postcss": "^6.0.1",
    "gulp-rename": "^1.2.0",
    "gulp-replace": "^0.5.3",
    "gulp-sass": "^2.2.0",
    "gulp-sourcemaps": "^1.6.0",
    "highlight.js": "^9.2.0",
    "jquery": "1.12.0",
    "jshint": "^2.8.0",
    "jshint-stylish": "^2.0.1",
    "mocha": "^2.2.4",
    "normalize.css": "3.0.3",
    "remarkable": "^1.6.2",
    "run-sequence": "^1.0.2"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "configs": {
    "paths": {
      "archive": "archive",
      "dist": "dist",
      "src": "src",
      "test": "test"
    }
  },
  "homepage": "https://html5boilerplate.com/",
  "license": {
    "type": "MIT",
    "url": "https://github.com/h5bp/html5-boilerplate/blob/master/LICENSE.txt"
  },
  "name": "html5-boilerplate",
  "private": true,
  "scripts": {
    "build": "gulp build",
    "test": "gulp archive && mocha --reporter spec --timeout 5000"
  },
  "version": "5.3.0",
  "dependencies": {
    "assemble": "^0.8.0",
    "designsystems-site-content": "git+ssh://git@git.target.com:design-systems/designsystems-site-content.git",
    "engine-handlebars": "0.8.0",
    "gulp-debug": "^2.1.2",
    "gulp-extname": "^0.2.2",
    "merge-stream": "^1.0.0",
    "target-base-library": "git+ssh://git@git.target.com:design-systems/base-pattern-library.git",
    "a11y-content": "git+ssh://git@git.target.com:design-systems/accessibility-content.git"

  }
}
`

**Comment by doowb** [comment]
If you upgrade to `assemble@latest` which is `0.9.1` do you still have problems?

**Comment by julianomoreira** [comment]
@doowb It did work. Thanks!

**Comment by StephanGerbeth** [comment]
using version 0.9.1 -> same issue. it doesn't work.

**Comment by StephanGerbeth** [comment]
when i downgrade to base-cli version 0.4.16 it works.

**Comment by doowb** [comment]
@julianomoreira we're working on setting up a way to tweet automatically when new versions are published. Other than that, we try to follow semver and tag releases on github (I think you will see those in your feed if you're watching a project).

@StephanGerbeth did you reinstall all the dependencies or just do assemble? I'm finding with npm@3 I have to delete my `node_modules`, clear the npm cache (`npm cache clear`) and reinstall (`npm i`) otherwise some modules don't get updated.

**Comment by doowb** [comment]
> We just span off a small team within Target to build Design Systems on Assemble

@julianomoreira that's great! Please feel free to post any projects and/or results in the [Who uses Assemble?](https://github.com/assemble/assemble/issues/300) issue.

**Comment by julianomoreira** [comment]
@doowb For sure. We will soon. Thanks!

**Comment by jonschlinkert** [comment]
> Let me know if this is the right forum for this.

I think you came to the right place. (no worries either way, it's our responsibility to help users find the right place)

It's great to hear that you're using assemble at Target. Let us know if you have questions, or feel free to join the conversation on [gitter](https://gitter.im/assemble/assemble).

**Comment by julianomoreira** [comment]
@jonschlinkert Thanks! We just started with Assemble not too long ago so there's a bit of a learning curve for us. I'll checkout Gitter. Thanks again!

**Comment by jonschlinkert** [comment]
any time!

**Comment by StephanGerbeth** [comment]
Yeah i didn't cleaned the cache. Sorry!

**Comment by jonschlinkert** [comment]
Sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if your still having problems.
